### ISSUE TITLE
maxRanges needs more documentation to clarify how to use it

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-languageserver-protocol-foldingprovider#3]
The [protocol](https://github.com/Microsoft/vscode-languageserver-protocol-foldingprovider/blob/ebc19ced18b67735cd9d31ffe26f0efa90d71f45/protocol.foldingProvider.md) currently states the following:
```TypeScript
export interface FoldingRangeRequestParam {
	/**
	 * The text document.
	 */
	textDocument: TextDocumentIdentifier;

	/**
	 * The maximum number of ranges to provide
	 */
	maxRanges?: number;
}
```
How can a client specify that the server should return "all" possible ranges in the document? Should `Number.MAX_SAFE_INTEGER` be used? Should a negative number be used? Or should a negative number in `maxRanges` cause the server to throw an error back to the client?

**Comment by aeschli** [comment]
It's an optional argument. So without max defined, all ranges should be returned.

I'll update the spec.

**Comment by rcjsuen** [comment]
Closing as 0a33073c7347aaa8995f70319137d415ff665627 has removed this property.
