### ISSUE TITLE
FoldingRange interfaces don't match and needs more clarification

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-languageserver-protocol-foldingprovider#6]
The [Markdown file](https://github.com/Microsoft/vscode-languageserver-protocol-foldingprovider/blob/ebc19ced18b67735cd9d31ffe26f0efa90d71f45/protocol.foldingProvider.md) defines the following:
```TypeScript
/**
 * Represents a folding range.
 */
export interface FoldingRange {

	/**
	 * The start line number of the folding range. The first line will stay visible, all folloing lines, including the end line will be folded.
	 */
	startLine: number;

	/**
	 * The end line number. The last line will be hidden.
	 */
	endLine: number;

	/**
	 * The type of folding range.
	 */
	type?: FoldingRangeType | string;
}
```
The [TypeScript file](https://github.com/Microsoft/vscode-languageserver-protocol-foldingprovider/blob/ebc19ced18b67735cd9d31ffe26f0efa90d71f45/src/protocol.foldingProvider.ts) defines the following:
```TypeScript
/**
 * Represents a folding range.
 */
export interface FoldingRange {

	/**
	 * The start line number of the folding range.
	 */
	startLine: number;

	/**
	 * The start column of the folding range. If not set, this defaults to the length of the start line.
	 */
	startColumn?: number;

	/**
	 * The end line number. The last line will be hidden.
	 */
	endLine: number;

	/**
	 * The start column of the folding range. If not set, this defaults to the length of the end line.
	 */
	endColumn?: number;

	/**
	 * The type of folding range.
	 */
	type?: FoldingRangeType | string;
}
```

I'm assuming that the TypeScript one is correct with `startColumn` and `endColumn`?

Are "lines" and "columns" zero-based or one-based?

What is a "column"? Is it the space between two characters (similar to the LSP `Position`)? If it's zero-based and has a value of `0` then it is the beginning of the line? In Windows' Notepad, columns are one-based and a value of `1` puts it at the beginning of the line.

Or is a "column" the actual space that is taken up by a character?

**Comment by patrys** [comment]
Is there a reason it does not simply use `range: Range` as the LSP already defines this type?

**Comment by aeschli** [comment]
Thanks for the great feedback. I meant to use 'character', not column.
I prefer to not use Range as the character properties are optional. 

Please check out the updated comments
